language: node_js
node_js:
  - 11.7.0
env:
  global:
    - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
script:
  - yarn test
deploy:
  provider: npm
  email: steveruizok@gmail.com
  api_key:
    secure: not-secure
on:
    tags: false
    repo: steveruizok/use-motion-resize-observer
    branch: master
  skip_cleanup: true
